In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
print(torch.__version__)
!nvcc --version

2.4.1+cu121
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


## Introduction to Tensors


### Creating Tensors

In [3]:
# Scalar (variable in lowercase)
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
# Get tensor back as Python datatype
print(scalar.item())
type(scalar.item())

7


int

In [7]:
# Vector (variable in uppercase)

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix (variable in uppercase)

MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
# Tensor (variable in uppercase)
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors


Random tensors are important because when neural networks learn they start with tensor of random numbers and then adjust those random numbers to better represent the data.

Default Datatype : float32

In [18]:
# Creating a random tensor of shape (n,m)
# values between 0 and 1
random_tensor=torch.rand(3,5,4)
random_tensor

tensor([[[0.6297, 0.4881, 0.5448, 0.3521],
         [0.0945, 0.3802, 0.3709, 0.2117],
         [0.4639, 0.7932, 0.7226, 0.4899],
         [0.5249, 0.2738, 0.9463, 0.1932],
         [0.7688, 0.8867, 0.6576, 0.2867]],

        [[0.4818, 0.3813, 0.1726, 0.7533],
         [0.2510, 0.6922, 0.5338, 0.0263],
         [0.0094, 0.5633, 0.7614, 0.6035],
         [0.9805, 0.5661, 0.3043, 0.5758],
         [0.9590, 0.9879, 0.0136, 0.7144]],

        [[0.8034, 0.3855, 0.8969, 0.3953],
         [0.2437, 0.4268, 0.7118, 0.2778],
         [0.7458, 0.8579, 0.8067, 0.5820],
         [0.4172, 0.1584, 0.7500, 0.1907],
         [0.1124, 0.6104, 0.5579, 0.9662]]])

In [19]:
random_tensor.ndim

3

In [20]:
# creating a tensor with the shape of an image
image_tensor=torch.rand(size=(224,224,3)) #height,width,color channel
image_tensor.shape,image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zero's and One's Tensors

In [21]:
zero_tensor=torch.zeros(3,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
one_tensor=torch.ones(2,4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
one_tensor.dtype,zero_tensor.dtype

(torch.float32, torch.float32)

## Creating range of tensors and tensors-like

In [24]:
# using torch.range()
torch.range(0,10)

<ipython-input-24-d2c2c3246a87>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
t1=torch.arange(start=0,end=100,step=7)
t1

tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [26]:
# creating tensor like
# creates a tensor which has the same shape as the input
tensor_like_t1=torch.zeros_like(input=t1)
tensor_like_t1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into Pytorch & deep Learning:

1. Tesnors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
# default datatype for tensor is float 32
t1=torch.tensor([3.01,5.92,6.83])
t1,t1.dtype

(tensor([3.0100, 5.9200, 6.8300]), torch.float32)

In [28]:
# To create a tensor of a particulat datatype use the dtype argument
t2=torch.tensor([3.1,9.3,7.2],dtype=torch.float16)
t2,t2.dtype

(tensor([3.0996, 9.2969, 7.1992], dtype=torch.float16), torch.float16)

In [29]:
# 3 important argument for thesor function
t3=torch.tensor([1.0,4.9,2.8],
                dtype=None, #datatype of the tensor
                device=None, #cpu or cuda
                requires_grad=False) #whether or not to track gradients with the tensor operations

In [30]:
#convert to flaot 16
float_16_tensor=t1.type(torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from tensors
1. get datatype of tensor - `tensor.dtype`
2. get shape of tensor - `tensor.shape`
3. get device from the tensor - `tensor.device`

In [31]:
# create a tensor
t1=torch.rand((3,4))
t1

tensor([[0.6793, 0.0363, 0.0717, 0.6836],
        [0.3344, 0.8098, 0.8049, 0.7548],
        [0.8991, 0.6550, 0.0445, 0.4506]])

In [32]:
print("Tensor:\n",t1)
print(f"Data type: {t1.dtype}")
print(f"Shape of tensor: {t1.shape}") # t1.size()
print(f"Device of tensor: {t1.device}")

Tensor:
 tensor([[0.6793, 0.0363, 0.0717, 0.6836],
        [0.3344, 0.8098, 0.8049, 0.7548],
        [0.8991, 0.6550, 0.0445, 0.4506]])
Data type: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Tensor operations
 * Addition
 * Subtraction
 * Multiplication (element-wise)
 * Division
 * Matrix multiplication

In [33]:
t1=torch.tensor([1,2,3])
#Addition
t1+10
# t1+t1

tensor([11, 12, 13])

In [34]:
#Multiplication
t1*10
# t1*t1

tensor([10, 20, 30])

In [35]:
# Subtraction
t1-10
# t1-t1

tensor([-9, -8, -7])

In [36]:
# Inbuilt functions
torch.mul(t1,7)
torch.add(t1,9)

tensor([10, 11, 12])

In [37]:
# Matrix Multipication or Dot product (most common operation in Neural networks)
mat_multi=torch.matmul(t1,t1)
mat_multi

tensor(14)

In [38]:
%%time
value=0
for i in range(len(t1)):
  value+=t1[i]*t1[i]
print(value)

tensor(14)
CPU times: user 1.81 ms, sys: 30 µs, total: 1.84 ms
Wall time: 1.71 ms


In [39]:
%%time
torch.matmul(t1,t1)

CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 40.8 µs


tensor(14)

In [40]:
%%time
t1@t1

CPU times: user 61 µs, sys: 11 µs, total: 72 µs
Wall time: 76.5 µs


tensor(14)

Two main rules that matrix multiplication must satisfy:
1. The **inner dimensions** must match.
  * `(3,2) @ (3,2) won't work`
  * `(2,3) @ (3,2) will work`
  * `(3,2) @ (2,3) will work`
2. The resulting matrix has shape of outer dimension
  * `(2,3) @ (3,2)` -> Result shape :`(2,2)`
  * `(3,2) @ (2,3)` -> Result shape :`(3,3)`

In [41]:
#torch.matmul(torch.rand(3,2),torch.rand(3,2))

In [42]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1206, 0.3726, 0.0590],
        [0.2287, 0.6447, 0.1367],
        [0.2924, 0.9568, 0.1216]])

One of the most common error in deep learning: Shape error
-> To fix the shape issues, we can manupilate the shape of one of the tensor using the **Transpose**

In [43]:
tensor_A=torch.rand((3,2))
tensor_B=torch.rand((3,2))
tensor_A,tensor_B

(tensor([[0.9966, 0.6556],
         [0.8803, 0.5113],
         [0.3785, 0.1695]]),
 tensor([[0.4141, 0.7433],
         [0.7607, 0.3095],
         [0.5730, 0.1495]]))

In [44]:
# tensor_A and tensor_B matrix multiplication is not possible, so we transpose
torch.mm(tensor_A,tensor_B.T)

tensor([[0.9000, 0.9611, 0.6691],
        [0.7446, 0.8279, 0.5809],
        [0.2828, 0.3404, 0.2423]])

## Tensor Aggregation -Min, Max, mean and Sum

In [45]:
t1=torch.arange(1,1000,10)
t1

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271,
        281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391, 401, 411,
        421, 431, 441, 451, 461, 471, 481, 491, 501, 511, 521, 531, 541, 551,
        561, 571, 581, 591, 601, 611, 621, 631, 641, 651, 661, 671, 681, 691,
        701, 711, 721, 731, 741, 751, 761, 771, 781, 791, 801, 811, 821, 831,
        841, 851, 861, 871, 881, 891, 901, 911, 921, 931, 941, 951, 961, 971,
        981, 991])

In [46]:
#Find Minimum
torch.min(t1) #or t1.min()

tensor(1)

In [47]:
#Find Maximum
torch.max(t1) #or t1.max()

tensor(991)

In [48]:
#Find mean
torch.mean(t1.type(torch.float32)),t1.type(torch.float32).mean()  #the input tensor cannot be complex type like long so we convert to flaot32

(tensor(496.), tensor(496.))

In [49]:
# find sum
torch.sum(t1),t1.sum()

(tensor(49600), tensor(49600))

In [50]:
#find the index of max element in tensor
torch.argmax(t1),t1.argmax()

(tensor(99), tensor(99))

In [51]:
#find the index of min element in tensor
torch.argmin(t1),t1.argmin()

(tensor(0), tensor(0))

## Reshaping, Viewing, Stacking, Squeezing, Unsqueezing and permute


* Reshaping - reshapes an input tensor to a defined shape.
* View - returns a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes all `1` deimensions from the tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [52]:
t1=torch.arange(1.,100.,10)
t1.shape

torch.Size([10])

In [53]:
#Reshape
reshaped=t1.reshape(2,5)
t1,reshaped,reshaped.shape

(tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.]),
 tensor([[ 1., 11., 21., 31., 41.],
         [51., 61., 71., 81., 91.]]),
 torch.Size([2, 5]))

In [54]:
# Change the view
# Changing z changes t1 as a view of a tensor shares the same memory as the original input

z=t1.view(5,2)


z[:,0]=100
z,z.shape,t1

(tensor([[100.,  11.],
         [100.,  31.],
         [100.,  51.],
         [100.,  71.],
         [100.,  91.]]),
 torch.Size([5, 2]),
 tensor([100.,  11., 100.,  31., 100.,  51., 100.,  71., 100.,  91.]))

In [55]:
#Stack tensors
t1_stacked=torch.stack([t1,t1,t1,t1],dim=0)
t1_stacked

tensor([[100.,  11., 100.,  31., 100.,  51., 100.,  71., 100.,  91.],
        [100.,  11., 100.,  31., 100.,  51., 100.,  71., 100.,  91.],
        [100.,  11., 100.,  31., 100.,  51., 100.,  71., 100.,  91.],
        [100.,  11., 100.,  31., 100.,  51., 100.,  71., 100.,  91.]])

In [56]:
#Squeezed
x=torch.arange(0,10)

x_reshaped=x.reshape(1,10)
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')
x_squeezed=x_reshaped.squeeze()
print(f'Previous tensor: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

Previous tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 10])
Previous tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([10])


In [57]:
#Unsqueezed

x_squeezed=x_reshaped.squeeze()
print(f'Previous tensor: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')
x_unsqueezed=x_squeezed.unsqueeze(dim=0)  #if dim=1 we get shape [10,1]
print(f'Previous tensor: {x_unsqueezed}')
print(f'Previous shape: {x_unsqueezed.shape}')

Previous tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([10])
Previous tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 10])


In [58]:
# permute -rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=[254,254,3])
x_permute=x_original.permute(2,0,1)
print(f'Original shape :{x_original.shape}\nPermuted shape: {x_permute.shape}')

Original shape :torch.Size([254, 254, 3])
Permuted shape: torch.Size([3, 254, 254])


## Indexing (selecting data from tensor)

In [59]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
x[0,1] #or x[0][1]

tensor([4, 5, 6])

In [62]:
x[0,2,1] #or x[0][2][1]

tensor(8)

In [63]:
x[0,2,2]

tensor(9)

In [64]:
x[:,0]

tensor([[1, 2, 3]])

In [65]:
#Get all values of the 0th dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
#Get all values of the 0th dimension but only 1 index value of the 1st and 2nd dimesion
x[:,1,1]

tensor([5])

In [67]:
# get index 0 of the 0th dimension and all values of the 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [68]:
# index on x to return 9
x[:,2,2]

#index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch Tensors and Numpy

* Convert Numpy (ndarray) to torch tensor -> `torch.from_numpy(ndarray)`
* Convert a torch tensor to numpy ndarray -> `torch.Tensor.numpy()`





In [69]:
import torch
import numpy as np


#numpy to tensor
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)  #It returns a float64 as the default, because the default datatype in numpy is float64

print('Numpy Array',array,'\nData Type',array.dtype)
print('Tensor',tensor,'\nTensor Datatype',tensor.dtype)

# convert float64 to float 32
tensor1=torch.from_numpy(array).type(torch.float32)
print('Tensor (type float32)',tensor1,'\nTensor Datatype',tensor1.dtype)

Numpy Array [1. 2. 3. 4. 5. 6. 7.] 
Data Type float64
Tensor tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) 
Tensor Datatype torch.float64
Tensor (type float32) tensor([1., 2., 3., 4., 5., 6., 7.]) 
Tensor Datatype torch.float32


In [70]:
array[0]=100
array,tensor1,tensor

(array([100.,   2.,   3.,   4.,   5.,   6.,   7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.], dtype=torch.float64))

In [71]:
#Tensor to numpy
tensor__=torch.ones(5)
numpy_array=tensor__.numpy()
tensor__,tensor__.dtype,numpy_array,numpy_array.dtype

(tensor([1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [72]:
#change the tensor
tensor__[0]=100
numpy_array,tensor__

(array([100.,   1.,   1.,   1.,   1.], dtype=float32),
 tensor([100.,   1.,   1.,   1.,   1.]))

## Reproducibility

To reduce the randomness and increase the reproducibility we use the concept of **random seed**

[Pytorch Reproducibility](https://pytorch.org/docs/stable/notes/randomness.html)

In [73]:
tensorA=torch.rand(3,4)
tensorB=torch.rand(3,4)

print('Tensor A',tensorA)
print('Tensor B',tensorB)
print(tensorA==tensorB)

Tensor A tensor([[0.1250, 0.8701, 0.6021, 0.4910],
        [0.4473, 0.3770, 0.5977, 0.5015],
        [0.3338, 0.5024, 0.9144, 0.0665]])
Tensor B tensor([[0.8554, 0.7545, 0.5600, 0.7924],
        [0.5697, 0.7804, 0.4510, 0.8648],
        [0.9353, 0.9875, 0.4879, 0.7273]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [74]:
#Random but reproducible tensor
RANDOM_SEED=42

torch.manual_seed(RANDOM_SEED)
tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
tensor_D=torch.rand(3,4)

print('Tensor A',tensor_C)
print('Tensor B',tensor_D)
print(tensor_C==tensor_D)

Tensor A tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor B tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on GPU's

* Use google co-lab
* Using own GPU resources
* Use cloud

In [75]:
!nvidia-smi

Mon Sep 23 06:31:21 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [76]:
#Check GPU access using Pytorch
import torch
torch.cuda.is_available()

True

In [77]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
#Count the number of GPU
torch.cuda.device_count()

1

For Pytorch ,as it is capable of running compute on the GPU or CPU, its best practice to setup device agnostic code.

Eg. Run on GPU if available else CPU

## Putting Tensors (and models) on the GPU

In [79]:
tensor=torch.tensor([1,2,3],device='cpu')
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [80]:
# move tensor to GPU if available
tensor_gpu=tensor.to(device)
tensor,tensor_gpu.device

(tensor([1, 2, 3]), device(type='cuda', index=0))

In [81]:
# If tensor is on GPU, we cannot transform it to numpy. So, we move tensor back to cpu
tensor_cpu=tensor_gpu.cpu()
tensor_cpu,tensor_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))